### ISSUE TITLE
archetype-2.2.0 release fails to download scriptom:1.6.0

### ISSUE THREAD

**Issue by noschinl** [seu-as-code/seu-as-code.archetype#12]
For the archetype, build.gradle specifies

```
seuac 'org.codehaus.groovy.modules.scriptom:scriptom:1.6.0'
```

as a dependency. However, the 2.2.0 release fails to download this dependency:

```
$ ./gradlew bootstrapSeu

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'seuac-archetype-2.2.0'.
> Could not resolve all dependencies for configuration ':seuac'.
   > Could not resolve org.codehaus.groovy.modules.scriptom:scriptom:1.6.0.
     Required by:
         :seuac-archetype-2.2.0:1.0
      > Could not resolve org.codehaus.groovy.modules.scriptom:scriptom:1.6.0.
         > Could not parse POM https://dl.bintray.com/seu-as-code/maven/org/codehaus/groovy/modules/scriptom/scriptom/1.6.0/scriptom-1.6.0.pom
            > Could not find org.codehaus.groovy.modules.scriptom:scriptom-module-pom:1.6.0.
              Searched in the following locations:
                  file:/V:/seuac-archetype-2.2.0/repo/scriptom-module-pom-1.6.0.jar
                  file:/V:/seuac-archetype-2.2.0/repo/scriptom-module-pom.jar
                  https://dl.bintray.com/seu-as-code/maven/org/codehaus/groovy/modules/scriptom/scriptom-module-pom/1.6.0/scriptom-module-pom-1.6.0.pom
                  https://dl.bintray.com/seu-as-code/maven/org/codehaus/groovy/modules/scriptom/scriptom-module-pom/1.6.0/scriptom-module-pom-1.6.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.344 secs
```

**Comment by seu-as-code** [comment]
I tried to make the basic SEU setup independent of Maven Central. Seems I forgot to include the parent POM of Scriptom in the Bintray repo.

As a quick workaround, try declaring jcenter() additionally in the repositories section.

``` groovy
repositories {
    flatDir { dirs 'repo' }
    maven {
        url 'https://dl.bintray.com/seu-as-code/maven'
    }
    jcenter()
}
```

**Comment by seu-as-code** [comment]
Started uploading the missing POM to the Binary repo. Then Jacob is missing. Uploaded this one. Then Groovy 1.6.0 is missing and all its transitive dependencies. And so on.

So I think instead of replicating all required dependencies, it is easier to just use jcenter() as an additional repo per default.

**Comment by noschinl** [comment]
Worked for me till it got to the 'com.jetbrains:intellij:15.0.3:win' dependency. But maybe I need to build this dependency myself, first?

**Comment by lreimer** [comment]
Correct. Not all software package dependencies are nor will be available as dependency via Bintray, since it only allows the upload for open source licensed artifacts.
Since IntelliJ Ultimate is a commercial software you have to build this dependency yourself and upload it to your own company repo server for example. 
Clone the https://github.com/seu-as-code/seu-as-code.packages.git repo. And then use `gradlew buildPackage` to download and build the artifact yourself.
